# -*- coding: utf-8 -*-
"""Activity.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SJUsSrZlzs3R32ksUcALKBocVqgdp_Xg
"""

import pandas as pd
data = pd.read_excel("/content/House.xlsx")
data

data.info()

data.describe()

import pandas as pd
import matplotlib.pyplot as plt

from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, mean_squared_error

data = pd.DataFrame({
    "House_size(Sqft)": [600, 750, 900, 1100, 1250],
    "H_price": [1200000, 1500000, 2000000, 2400000, 3300000]
})

print(data.info())
print(data.describe())

X = data[["House_size(Sqft)"]]
y = data["H_price"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

model = LinearRegression()
model.fit(X_train, y_train)

predicted = model.predict([[1700]])
print("The predicted price for 1700 Sqft is:", predicted)

y_pred = model.predict(X)

print("R2 Score:", r2_score(y, y_pred))
print("Mean Squared Error:", mean_squared_error(y, y_pred))

plt.scatter(X, y, color="black", label="Actual Price")
plt.plot(X, y_pred, color="red", label="Regression Line")
plt.xlabel("House Size (Sqft)")
plt.ylabel("House Price")
plt.title("House Price Prediction")
plt.grid(linestyle="--")
plt.legend()
plt.show()

import pandas as pd
import matplotlib.pyplot as plt

from sklearn.preprocessing import PolynomialFeatures
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_squared_error

data = pd.DataFrame({
    "study2_h": [1, 2, 3, 4, 5],
    "marks": [20, 30, 55, 78, 90]
})

X = data[["study2_h"]]
y = data["marks"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

poly = PolynomialFeatures(degree=2)

X_poly = poly.fit_transform(X)
X_train_poly = poly.fit_transform(X_train)
X_test_poly = poly.transform(X_test)

model = LinearRegression()
model.fit(X_train_poly, y_train)

prediction = model.predict(poly.transform([[8]]))
print("The prediction value for 8 hours is:", prediction)

predicted = model.predict(X_poly)

print("R2 Score:", r2_score(y, predicted))
print("Mean Squared Error:", mean_squared_error(y, predicted))

plt.scatter(X, y, color="blue", label="Actual Data")
plt.plot(X, predicted, color="red", label="Polynomial Curve")
plt.xlabel("Study Hours")
plt.ylabel("Marks")
plt.title("Polynomial Regression")
plt.grid(linestyle="--")
plt.legend()
plt.show()

import pandas as pd
import matplotlib.pyplot as plt

from sklearn.preprocessing import PolynomialFeatures
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_squared_error

data = pd.DataFrame({
    "Experience_y": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    "salary": [30000, 35000, 45000, 60000, 80000, 105000, 140000, 180000, 230000, 230000]
})

X = data[["Experience_y"]]
y = data["salary"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

poly = PolynomialFeatures(degree=2)

X_train_poly = poly.fit_transform(X_train)
X_test_poly = poly.transform(X_test)
X_poly = poly.transform(X)

model = LinearRegression()
model.fit(X_train_poly, y_train)

prediction = model.predict(poly.transform([[380000]]))
print("The predicted salary for 12 years experience is:", prediction)

predicted = model.predict(X_poly)

print("R2 Score:", r2_score(y, predicted))
print("Mean Squared Error:", mean_squared_error(y, predicted))

plt.scatter(X, y, color="blue", label="Actual Data")
plt.plot(X, predicted, color="red", label="Polynomial Curve")
plt.xlabel("Experience (Years)")
plt.ylabel("Salary")
plt.title("Polynomial Regression")
plt.grid(linestyle="--")
plt.legend()
plt.show()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures


data = {
    "Experience": [1,2,3,4,5,6,7,8,9,10],
    "Salary": [30000,40000,50000,65000,80000,100000,130000,170000,220000,300000]
}

df = pd.DataFrame(data)

X = df[["Experience"]]
y = df["Salary"]

linear_model = LinearRegression()
linear_model.fit(X, y)

y_linear = linear_model.predict(X)

poly = PolynomialFeatures(degree=2)

X_poly = poly.fit_transform(X)

poly_model = LinearRegression()
poly_model.fit(X_poly, y)

X_new = np.linspace(1, 10, 100).reshape(-1, 1)
X_new_poly = poly.transform(X_new)

y_poly = poly_model.predict(X_new_poly)

plt.figure(figsize=(12,5))

plt.subplot(1,2,1)

plt.scatter(
    df["Experience"],
    df["Salary"],
    color="red",
    label="Original Data"
)

plt.plot(
    df["Experience"],
    y_linear,
    color="blue",
    linewidth=2,
    label="Linear Regression"
)

plt.xlabel("Experience (Years)")
plt.ylabel("Salary")
plt.title("Linear Regression")
plt.grid(True)
plt.legend()

plt.subplot(1,2,2)

plt.scatter(
    df["Experience"],
    df["Salary"],
    color="red",
    label="Original Data"
)

plt.plot(
    X_new,
    y_poly,
    color="green",
    linewidth=2,
    label="Polynomial Regression"
)

plt.xlabel("Experience (Years)")
plt.ylabel("Salary")
plt.title("Polynomial Regression")
plt.grid(True)
plt.legend()

plt.tight_layout()
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.svm import SVR
from sklearn.metrics import r2_score,mean_squared_error

df = pd.DataFrame({
    "Temp":[18,20,22,24,25,28,30,32,34,36],
    "Ice": [45,55,70,90,115,140,170,195,215,230]
})
df

X = df[["Temp"]]
y = df["Ice"]

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3)

model = SVR(kernel="rbf")

model.fit(X,y)
predict = model.predict(X)
print("The temp prediction value is :", model.predict([[45]]))

print(" R2_Score value is:", r2_score(y,predict))
print(" MSE value is :", mean_squared_error(y,predict))

plt.scatter(X,y,color="blue", label="Actual Data")
plt.plot(X, predict,color="red", label="SVR line")
plt.grid()
plt.show()

import pandas as pd
data = pd.read_excel("/content/Ice.xlsx")
data

